### PR TITLE
include <cstdint> to fix compiling with gcc13

### PR DESCRIPTION
**Pull request by shun2wang**
will fix jaspBase [rcmd check ](https://github.com/shun2wang/jaspBase/actions/runs/9062177217)fail on Windows R4.4.0+ see:https://github.com/jasp-stats/jaspBase/pull/148. also fix jaspBase compile to install.

### CODE REVIEW

**Comment by shun2wang** [comment]
@JorisGoosen @boutinb Should we also keep these files caught up with new changes in [jasp-desktop](https://github.com/jasp-stats/jasp-desktop/tree/development/Common) repo? Seems to be a consistent goal but this repo is lagging far behind.

Or perhaps these two repositories should be organized in another way? such as submodules or fetch up form main...?

**Comment by JorisGoosen** [comment]
> @JorisGoosen @boutinb Should we also keep these files caught up with new changes in [jasp-desktop](https://github.com/jasp-stats/jasp-desktop/tree/development/Common?rgh-link-date=2024-05-14T07%3A56%3A13Z) repo? Seems to be a consistent goal but this repo is lagging far behind.
> 
> Or perhaps these two repositories should be organized in another way? such as submodules or fetch up form main...?

yeah this was organised differently before indeed.
This submodule was shared!

Im not sure why we are now using both of these.

**Comment by JorisGoosen** [comment]
No, ill just put the submodule back...

**Comment by shun2wang** [comment]
and also https://github.com/jasp-stats/jaspResults used this repo I guess.

**Comment by JorisGoosen** [comment]
Yeah indeed, but that got merged into jaspBase a while ago

**Pull request merged**
